### ISSUE TITLE
root not working 

### ISSUE THREAD

**Issue by studentforcode** [DanWin/mail-hosting#22]
Hello, 
on my site the root is /var/www/exmple/www 
firstly, database changes in common_config.php and mail-hosting-main\tools\mass_mail\index.php then uploaded the files to server.

secondly,  ./install_binaries.sh ,  ./install_binaries_proxy.sh,  ./update-translation.sh  
I relized that all my sql datbase has been removed ,  why cant acces the site file on http ? is there any necessary changes ? 
thanks

**Comment by DEAM0** [comment]
> Hello, on my site the root is /var/www/exmple/www firstly, database changes in common_config.php and mail-hosting-main\tools\mass_mail\index.php then uploaded the files to server.
> 
> secondly, ./install_binaries.sh , ./install_binaries_proxy.sh, ./update-translation.sh I relized that all my sql datbase has been removed , why cant acces the site file on http ? is there any necessary changes ? thanks

The documentation is not yet complete.  I also thought I could do it myself, but I'm waiting for Daniel to write this documentation.  There are extremely many files to change, domains, storage.  No one can help you with this until the documentation is complete.

**Comment by DanWin** [comment]
@studentforcode as discussed by email, you tried uploading the files to a web hosting, which won't work because you need at least 2 VPS for this setup. Also the issue was file permissions not being set right so that your web sever was unable to access those files.

**Comment by studentforcode** [comment]
Yes, thanks senior .
